feat: tests implementation documentation and additions to conventions
SurprisedBird/MurderBattleConsole pull request #10
Opened 2020-07-08 23:34 UTC by asternotus

1. Add steps to set up and run tests into the ENVIRONMENT_SETUP.md
2. Add Quotes and Conditionals rules into the CODE_CONVENTIONS.md

2020-07-09 09:33 UTC, elias-gvin requested changes

2020-07-09 09:33 UTC, elias-gvin commented on docs/ENVIRONMENT_SETUP.md
> +## Unit tests implementation
Great instruction!
But I rather meant simple copy/paste settings instruction, like in:
https://github.com/SurprisedBird/MurderBattleConsole/blob/71e8897b07cfa175c8e5c72f8987ee6351cd9842/docs/ENVIRONMENT_SETUP.md#enable-code-formatting-in-vscode

2020-07-09 09:33 UTC, elias-gvin commented on docs/ENVIRONMENT_SETUP.md
> +## Unit tests implementation
I suggest you to move your detail test instruction in a separate .md file.
But in this file you can leave a reference to your new .md file and, also a json snippet from your settings.json which will enable tests

2020-07-09 09:33 UTC, elias-gvin commented on docs/ENVIRONMENT_SETUP.md
> +2. Create __init__.py file in the "tests" folder
.md text format treats double underscore as mark to make text bold.
So, in formatted page we'll see not '\_\_init\_\_.py' but rather bold '__init__.py'

Please, fix problem with backslashes

2020-07-09 09:33 UTC, elias-gvin commented on docs/ENVIRONMENT_SETUP.md
> +4. Create __init__.py file in each subfolder
Same here

2020-07-09 09:33 UTC, elias-gvin commented on docs/CODE_CONVENTIONS.md
> +You should use brackets () for if/elif expressions in case "or" and "and" operators are used.
What should be used if there is no "or" and "and" statements? 
Ambiguous instruction

Suggestion: You can add "only" before "in case of ..."

2020-07-09 09:33 UTC, elias-gvin commented on docs/ENVIRONMENT_SETUP.md
> +6. from unittest import TestCase
Mb better (use ` symbol to mark import as a code snippet):

Add import:
`from unittest import TestCase`

2020-07-09 09:33 UTC, ADetilie commented on docs/CODE_CONVENTIONS.md
> +You should use only double quotes "" not never single quotes.
Still think that we should use single quotes for type hints.

You are right about single consistent style for every string. PEP8 declares:
https://www.python.org/dev/peps/pep-0008/#string-quotes
`In Python, single-quoted strings and double-quoted strings are the same. This PEP does not make a recommendation for this. Pick a rule and stick to it.`

but I don't think that they considered type hints in here.

Also, as far as I see, no one uses double quotes for type hints.
It seems like it is unspoken agreement.

Also, I'd like to separate visually strings that means types and strings which are used as... printable strings.

If you disagree with above statements, just leave a comment here, and we'll stick to rule with double-quotes.

2020-07-09 20:26 UTC, elias-gvin approved these changes

2020-07-10 19:01 UTC, SurprisedBird approved these changes

2020-07-11 10:10 UTC, merged