feat: Spy effect is implemented
SurprisedBird/MurderBattleConsole pull request #46
Opened 2021-03-13 00:49 UTC by asternotus

2021-03-13 01:07 UTC, ADetilie requested changes

2021-03-13 01:07 UTC, elias-gvin commented on effects/spy_effect.py
> +            self.game.active_player.hp -= 1
I'd rather use effect.creator than directly hit active player. But it is not principal

2021-03-13 01:07 UTC, elias-gvin commented on effects/spy_effect.py
> +        if self.game.spy.hp <= 0:
Please, use `is_alive` property for such cases

2021-03-14 01:56 UTC, asternotus commented on effects/spy_effect.py
> +            self.game.active_player.hp -= 1
Done

2021-03-14 01:57 UTC, asternotus commented on effects/spy_effect.py
> +        if self.game.spy.hp <= 0:
Done

2021-03-14 02:03 UTC, asternotus commented on effects/spy_effect.py
> +            self.game.active_player.hp -= 1
Why creator.
The spy is creator of SpyEffect
But I need reduce hp for ActivePlayer

Not change this logic

2021-03-14 11:04 UTC, ADetilie requested changes

2021-03-14 11:04 UTC, ADetilie commented on effects/spy_effect.py
> +            self.game.active_player.hp -= 1
@asternotus the creator of FOUND Kill\Steal\Stagin effect - not creator of SpyEffect

2021-03-15 01:45 UTC, ADetilie approved these changes

2021-03-15 01:45 UTC, merged