fix: syntax fixes of the actual develop
SurprisedBird/MurderBattleConsole pull request #9
Opened 2020-07-08 23:33 UTC by asternotus

1. read_number() is changed on the read_index() method in steal_effect.py
2. Fix errors with private variables in effect.py
3. Fix syntax error in "@abstractmethod" name and according import in effect.py

2020-07-09 06:43 UTC, ADetilie commented
Just a recommendation:
It is not necessary to provide such details in commit message about changes in current commit.
I believe that title provides enough details here:
changes in commit are trivial and speaks for themselves

2020-07-09 06:49 UTC, elias-gvin requested changes

2020-07-09 06:49 UTC, ADetilie commented on effects/effect.py
> +from abc import ABC, abstractmethod
Code style:
Don't perform several imports in one line.
Separate them, please.
from abc import ABC
from abc import abstractmethod

https://www.python.org/dev/peps/pep-0008/#imports

2020-07-09 20:27 UTC, ADetilie commented on effects/effect.py
> +from abc import ABC, abstractmethod
Automatic code formatter tells it is ok

2020-07-09 20:28 UTC, elias-gvin approved these changes

2020-07-10 19:02 UTC, SurprisedBird approved these changes

2020-07-11 10:05 UTC, merged